### ISSUE TITLE
Support Laravel 8.9

### ISSUE THREAD

**Issue by artemrogov** [mzur/laravel-openstack-swift#4]
Hi, Martin. You are about to enable Laravel 8. * support. Now when trying to install your package on the Laravel 8.9 framework, the following error appears:

run command: 
composer require mzur/laravel-openstack-swift

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mzur/laravel-openstack-swift ^1.11 -> satisfiable by mzur/laravel-openstack-swift[v1.11.0].
    - mzur/laravel-openstack-swift v1.11.0 requires illuminate/support ^5.1|^6.0|^7.0 -> found illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mzur** [comment]
I've released v1.12.0-beta which allows Laravel 8 as dependency. Please report back if this works correctly for you so I can create the actual release.

**Comment by artemrogov** [comment]
I have implemented your package in several of my projects. Thank you very much friend!
