### ISSUE TITLE
Need support for Laravel 10

### ISSUE THREAD

**Issue by sshaik305** [mzur/laravel-openstack-swift#6]
This is not supported for laravel 10 as dependencies like illuminate/support ^9.1 required

**Comment by mzur** [comment]
Hi, thanks for your interest in this package. I'm sure that all you need is add `^10` to the supported versions in the composer.json. Would you like to test if this works and send a PR?

**Comment by sshaik305** [comment]
https://github.com/mzur/laravel-openstack-swift/pull/7
