### ISSUE TITLE
404 not found /auth/tokens

### ISSUE THREAD

**Issue by divyeshccl** [mzur/laravel-openstack-swift#8]
Hello,

I'm trying to upload image and I received this error

`GuzzleHttp\Exception\ClientException: Client error: `POST https://cloud.xxx.net/v1/auth/tokens` resulted in a `404 NOT FOUND` response:
`
Can you please help me with that?

Thank you.

**Comment by mzur** [comment]
I suspect that auth URL is wrong. The package uses v3 of the identidy API and my URLs always had a `v3` at the end so I suggest trying `https://cloud.xxx.net/v3`.

**Comment by divyeshccl** [comment]
@mzur Thanks I resolved the issue with v3 and also I'm using port which I fail to add in URL.

Thank you.
